import SwiftUI

// Hand-curated category shelves. Cover IDs were resolved against the Open
// Library search API at curation time so shelves render without any search
// requests. Regenerate with the curation script if the lists change.
enum CuratedBooks {
    static func books(in category: BookCategory) -> [Book] {
        switch category {
        case .habits:
            return habits
        case .focus:
            return focus
        case .priorities:
            return priorities
        case .systems:
            return systems
        case .leadership:
            return leadership
        case .startup:
            return startup
        case .product:
            return product
        case .sales:
            return sales
        case .careers:
            return careers
        }
    }

    private static let habits: [Book] = [
        curated("Atomic Habits", "James Clear", 12539702, .habits),
        curated("The Power of Habit", "Charles Duhigg", 9078085, .habits),
        curated("Tiny Habits", "BJ Fogg", 9261174, .habits),
        curated("Good Habits, Bad Habits", "Wendy Wood", 10128464, .habits),
        curated("Better Than Before", "Gretchen Rubin", 12709821, .habits),
        curated("The Four Tendencies", "Gretchen Rubin", 10863058, .habits),
        curated("Mini Habits", "Stephen Guise", 8093714, .habits),
        curated("Elastic Habits", "Stephen Guise", 10093450, .habits),
        curated("High Performance Habits", "Brendon Burchard", 12385574, .habits),
        curated("The Compound Effect", "Darren Hardy", 7115046, .habits),
        curated("The Slight Edge", "Jeff Olson", 7285715, .habits),
        curated("The Willpower Instinct", "Kelly McGonigal", 9475786, .habits),
        curated("Willpower", "Roy F. Baumeister and John Tierney", 9082644, .habits),
        curated("How to Change", "Katy Milkman", 11121613, .habits),
        curated("Stick with It", "Sean D. Young", 10538639, .habits),
        curated("Triggers", "Marshall Goldsmith", 10996519, .habits),
        curated("The 5 Second Rule", "Mel Robbins", 8114155, .habits),
        curated("The Miracle Morning", "Hal Elrod", 8539416, .habits),
        curated("Discipline Equals Freedom", "Jocko Willink", 10464684, .habits),
        curated("Can't Hurt Me", "David Goggins", 8305903, .habits),
        curated("The Now Habit", "Neil Fiore", 8231849, .habits),
        curated("Solving the Procrastination Puzzle", "Timothy A. Pychyl", 7577549, .habits),
        curated("Drive", "Daniel H. Pink", 6404786, .habits),
        curated("Switch", "Chip Heath and Dan Heath", 6968365, .habits),
        curated("Nudge", "Richard H. Thaler and Cass R. Sunstein", 6402116, .habits),
        curated("The Power of Full Engagement", "Jim Loehr and Tony Schwartz", 5276864, .habits),
        curated("One Small Step Can Change Your Life", "Robert Maurer", 507718, .habits),
        curated("Habit Stacking", "S.J. Scott", 10213381, .habits),
        curated("Make Your Bed", "William H. McRaven", 7984714, .habits),
        curated("Awaken the Giant Within", "Tony Robbins", 4002352, .habits),
        curated("Grit", "Angela Duckworth", 7438753, .habits),
        curated("Peak", "Anders Ericsson and Robert Pool", 10467082, .habits),
        curated("The Talent Code", "Daniel Coyle", 11948223, .habits),
        curated("Mindset", "Carol S. Dweck", 746414, .habits),
        curated("The Practicing Mind", "Thomas M. Sterner", 743264, .habits),
        curated("Daily Rituals", "Mason Currey", 9283862, .habits),
        curated("Breaking the Habit of Being Yourself", "Joe Dispenza", 11348192, .habits),
        curated("Dopamine Nation", "Anna Lembke", 11757830, .habits),
        curated("Unwinding Anxiety", "Judson Brewer", 10721914, .habits),
        curated("The Craving Mind", "Judson Brewer", 14454811, .habits),
        curated("Superhuman by Habit", "Tynan", nil, .habits),
        curated("The War of Art", "Steven Pressfield", 288439, .habits),
        curated("Finish", "Jon Acuff", 8871060, .habits),
        curated("The Happiness Advantage", "Shawn Achor", 6938464, .habits),
        curated("The Motivation Myth", "Jeff Haden", 15152547, .habits),
        curated("Rewire", "Richard O'Connor", 12196070, .habits),
        curated("The Molecule of More", "Daniel Z. Lieberman and Michael E. Long", 10648753, .habits),
        curated("Hardwiring Happiness", "Rick Hanson", 11340722, .habits),
        curated("Two Awesome Hours", "Josh Davis", 8577472, .habits),
        curated("Feel-Good Productivity", "Ali Abdaal", 14635414, .habits),
    ]

    private static let focus: [Book] = [
        curated("Deep Work", "Cal Newport", 7988607, .focus),
        curated("Indistractable", "Nir Eyal", 9129784, .focus),
        curated("Stolen Focus", "Johann Hari", 12664855, .focus),
        curated("Hyperfocus", "Chris Bailey", 10239359, .focus),
        curated("Digital Minimalism", "Cal Newport", 8507540, .focus),
        curated("A World Without Email", "Cal Newport", 10328430, .focus),
        curated("Flow", "Mihaly Csikszentmihalyi", 11041932, .focus),
        curated("Finding Flow", "Mihaly Csikszentmihalyi", 298856, .focus),
        curated("The Shallows", "Nicholas Carr", 6458532, .focus),
        curated("Attention Span", "Gloria Mark", 13151982, .focus),
        curated("Free to Focus", "Michael Hyatt", 8805352, .focus),
        curated("The Distracted Mind", "Adam Gazzaley and Larry D. Rosen", 8882160, .focus),
        curated("Rapt", "Winifred Gallagher", 7986012, .focus),
        curated("Focus", "Daniel Goleman", 12672951, .focus),
        curated("The Rise of Superman", "Steven Kotler", 12512763, .focus),
        curated("The Art of Impossible", "Steven Kotler", 11590811, .focus),
        curated("Limitless", "Jim Kwik", 9360116, .focus),
        curated("Peak Performance", "Brad Stulberg and Steve Magness", 10405023, .focus),
        curated("Do Nothing", "Celeste Headlee", 9295715, .focus),
        curated("How to Break Up with Your Phone", "Catherine Price", 9269461, .focus),
        curated("10% Happier", "Dan Harris", 7277740, .focus),
        curated("The Miracle of Mindfulness", "Thich Nhat Hanh", 8262944, .focus),
        curated("Wherever You Go, There You Are", "Jon Kabat-Zinn", 749813, .focus),
        curated("Search Inside Yourself", "Chade-Meng Tan", 7983717, .focus),
        curated("Altered Traits", "Daniel Goleman and Richard J. Davidson", 9253925, .focus),
        curated("The Attention Merchants", "Tim Wu", 8868199, .focus),
        curated("Irresistible", "Adam Alter", 8843009, .focus),
        curated("Mindfulness in Plain English", "Bhante Henepola Gunaratana", 8015969, .focus),
        curated("Zen Mind, Beginner's Mind", "Shunryu Suzuki", 7025011, .focus),
        curated("The Power of Now", "Eckhart Tolle", 2401616, .focus),
        curated("Singletasking", "Devora Zack", 11714177, .focus),
        curated("The Twelve Monotasks", "Thatcher Wine", 13300625, .focus),
        curated("The Joy of Missing Out", "Tonya Dalton", 10313497, .focus),
        curated("Bored and Brilliant", "Manoush Zomorodi", 10142388, .focus),
        curated("Reclaiming Conversation", "Sherry Turkle", 7392421, .focus),
        curated("Alone Together", "Sherry Turkle", 6952623, .focus),
        curated("In Praise of Slowness", "Carl Honoré", 28811, .focus),
        curated("The Ruthless Elimination of Hurry", "John Mark Comer", 10211106, .focus),
        curated("Stillness Is the Key", "Ryan Holiday", 9130310, .focus),
        curated("24/6", "Tiffany Shlain", 8908150, .focus),
        curated("The Extended Mind", "Annie Murphy Paul", 8126013, .focus),
        curated("Your Brain at Work", "David Rock", 12936325, .focus),
        curated("Driven to Distraction", "Edward M. Hallowell and John J. Ratey", 424905, .focus),
        curated("ADHD 2.0", "Edward M. Hallowell and John J. Ratey", 10585093, .focus),
        curated("Scattered Minds", "Gabor Maté", 9532806, .focus),
        curated("Why We Sleep", "Matthew Walker", 8814155, .focus),
        curated("Rest", "Alex Soojung-Kim Pang", 10453387, .focus),
        curated("The Inner Game of Tennis", "W. Timothy Gallwey", 5413630, .focus),
        curated("The Mindful Athlete", "George Mumford", 12645275, .focus),
        curated("The Power of Concentration", "Theron Q. Dumont", 2889848, .focus),
    ]

    private static let priorities: [Book] = [
        curated("Essentialism", "Greg McKeown", 7285986, .priorities),
        curated("Effortless", "Greg McKeown", 10699081, .priorities),
        curated("The ONE Thing", "Gary Keller and Jay Papasan", 10351762, .priorities),
        curated("Four Thousand Weeks", "Oliver Burkeman", 11990973, .priorities),
        curated("Make Time", "Jake Knapp and John Zeratsky", 14179816, .priorities),
        curated("Eat That Frog!", "Brian Tracy", 847534, .priorities),
        curated("Slow Productivity", "Cal Newport", 14545976, .priorities),
        curated("First Things First", "Stephen R. Covey", 7001539, .priorities),
        curated("The 80/20 Principle", "Richard Koch", 241591, .priorities),
        curated("168 Hours", "Laura Vanderkam", 10618668, .priorities),
        curated("Tranquility by Tuesday", "Laura Vanderkam", 12553212, .priorities),
        curated("When", "Daniel H. Pink", 8552540, .priorities),
        curated("The Dip", "Seth Godin", 1977228, .priorities),
        curated("Hell Yeah or No", "Derek Sivers", 13176855, .priorities),
        curated("Subtract", "Leidy Klotz", 10252711, .priorities),
        curated("Die with Zero", "Bill Perkins", 10433791, .priorities),
        curated("The Top Five Regrets of the Dying", "Bronnie Ware", 9071458, .priorities),
        curated("A Guide to the Good Life", "William B. Irvine", 6958019, .priorities),
        curated("Boundaries", "Henry Cloud and John Townsend", 8227168, .priorities),
        curated("The Lazy Genius Way", "Kendra Adachi", 10224174, .priorities),
        curated("The Gap and the Gain", "Dan Sullivan and Benjamin Hardy", 11471538, .priorities),
        curated("10x Is Easier Than 2x", "Dan Sullivan and Benjamin Hardy", 13269048, .priorities),
        curated("Procrastinate on Purpose", "Rory Vaden", 8954775, .priorities),
        curated("The 5 Choices", "Kory Kogon, Adam Merrill, and Leena Rinne", 9512658, .priorities),
        curated("Time Management from the Inside Out", "Julie Morgenstern", 580583, .priorities),
        curated("Thinking in Bets", "Annie Duke", 8792782, .priorities),
        curated("Quit", "Annie Duke", 12537626, .priorities),
        curated("Decisive", "Chip Heath and Dan Heath", 8537216, .priorities),
        curated("The Paradox of Choice", "Barry Schwartz", 20382, .priorities),
        curated("Predictably Irrational", "Dan Ariely", 2314080, .priorities),
        curated("Margin", "Richard A. Swenson", 831807, .priorities),
        curated("How to Do Nothing", "Jenny Odell", 8750439, .priorities),
        curated("Meditations", "Marcus Aurelius", 211529, .priorities),
        curated("The Almanack of Naval Ravikant", "Eric Jorgenson", 10449931, .priorities),
        curated("Clear Thinking", "Shane Parrish", 15208264, .priorities),
        curated("The Great Mental Models", "Shane Parrish and Rhiannon Beaubien", 9778922, .priorities),
        curated("Buy Back Your Time", "Dan Martell", 13239151, .priorities),
        curated("Who Not How", "Dan Sullivan and Benjamin Hardy", 12412300, .priorities),
        curated("The 4-Hour Workweek", "Timothy Ferriss", 539652, .priorities),
        curated("Overwhelmed", "Brigid Schulte", 7319448, .priorities),
        curated("Time Smart", "Ashley Whillans", 831187, .priorities),
        curated("Happier Hour", "Cassie Holmes", 13105712, .priorities),
        curated("The Time Paradox", "Philip Zimbardo and John Boyd", 5407450, .priorities),
        curated("Your Money or Your Life", "Vicki Robin and Joe Dominguez", 6975229, .priorities),
        curated("The Psychology of Money", "Morgan Housel", 10389354, .priorities),
        curated("Enough", "John C. Bogle", 6917229, .priorities),
        curated("Wanting", "Luke Burgis", 10580856, .priorities),
        curated("The Second Mountain", "David Brooks", 8782644, .priorities),
        curated("Man's Search for Meaning", "Viktor E. Frankl", 11203708, .priorities),
        curated("The Obstacle Is the Way", "Ryan Holiday", 14428233, .priorities),
    ]

    private static let systems: [Book] = [
        curated("Getting Things Done", "David Allen", 109288, .systems),
        curated("Measure What Matters", "John Doerr", 10706481, .systems),
        curated("High Output Management", "Andrew S. Grove", 421244, .systems),
        curated("Smarter Faster Better", "Charles Duhigg", 12690321, .systems),
        curated("The Organized Mind", "Daniel J. Levitin", 7309773, .systems),
        curated("The Checklist Manifesto", "Atul Gawande", 8231866, .systems),
        curated("Building a Second Brain", "Tiago Forte", 12372866, .systems),
        curated("How to Take Smart Notes", "Sönke Ahrens", 8362230, .systems),
        curated("Algorithms to Live By", "Brian Christian and Tom Griffiths", 8042539, .systems),
        curated("Thinking in Systems", "Donella H. Meadows", 14420637, .systems),
        curated("The Fifth Discipline", "Peter M. Senge", 5306808, .systems),
        curated("Principles", "Ray Dalio", 8315355, .systems),
        curated("Traction: Get a Grip on Your Business", "Gino Wickman", 10678412, .systems),
        curated("The E-Myth Revisited", "Michael E. Gerber", 684209, .systems),
        curated("Work the System", "Sam Carpenter", 11119790, .systems),
        curated("The Goal", "Eliyahu M. Goldratt", 7262320, .systems),
        curated("The Phoenix Project", "Gene Kim, Kevin Behr, and George Spafford", 9151976, .systems),
        curated("The Toyota Way", "Jeffrey K. Liker", 58049, .systems),
        curated("Lean Thinking", "James P. Womack and Daniel T. Jones", 425241, .systems),
        curated("Scrum: The Art of Doing Twice the Work in Half the Time", "Jeff Sutherland", 8107216, .systems),
        curated("The 4 Disciplines of Execution", "Chris McChesney, Sean Covey, and Jim Huling", 9136687, .systems),
        curated("The 12 Week Year", "Brian P. Moran and Michael Lennington", 14632659, .systems),
        curated("Upstream", "Dan Heath", 9302230, .systems),
        curated("Super Thinking", "Gabriel Weinberg and Lauren McCann", 10153705, .systems),
        curated("The Personal MBA", "Josh Kaufman", 6713257, .systems),
        curated("Thinking, Fast and Slow", "Daniel Kahneman", 13290711, .systems),
        curated("Antifragile", "Nassim Nicholas Taleb", 9180157, .systems),
        curated("The Art of Action", "Stephen Bungay", 12400745, .systems),
        curated("Good Strategy Bad Strategy", "Richard Rumelt", 6954850, .systems),
        curated("Playing to Win", "A.G. Lafley and Roger L. Martin", 14507238, .systems),
        curated("Team of Teams", "Stanley McChrystal", 10522497, .systems),
        curated("Reinventing Organizations", "Frederic Laloux", 9159064, .systems),
        curated("Accelerate", "Nicole Forsgren, Jez Humble, and Gene Kim", 8509069, .systems),
        curated("Radical Focus", "Christina Wodtke", 10864735, .systems),
        curated("The Great CEO Within", "Matt Mochary", 10085060, .systems),
        curated("Scaling Up", "Verne Harnish", 8215424, .systems),
        curated("Who", "Geoff Smart and Randy Street", 10256089, .systems),
        curated("Work Rules!", "Laszlo Bock", 7346258, .systems),
        curated("The Life-Changing Magic of Tidying Up", "Marie Kondo", 7367218, .systems),
        curated("The PARA Method", "Tiago Forte", 14417094, .systems),
        curated("Where Good Ideas Come From", "Steven Johnson", 6602963, .systems),
        curated("Loonshots", "Safi Bahcall", 8518798, .systems),
        curated("Simple Rules", "Donald Sull and Kathleen M. Eisenhardt", 11087965, .systems),
        curated("The Bullet Journal Method", "Ryder Carroll", 10413432, .systems),
        curated("The Decision Book", "Mikael Krogerus and Roman Tschäppeler", 9955323, .systems),
        curated("Six Thinking Hats", "Edward de Bono", 4912485, .systems),
        curated("Out of the Crisis", "W. Edwards Deming", 703005, .systems),
        curated("Great by Choice", "Jim Collins and Morten T. Hansen", 7137774, .systems),
        curated("How Big Things Get Done", "Bent Flyvbjerg and Dan Gardner", 13247891, .systems),
        curated("Death by Meeting", "Patrick Lencioni", 871701, .systems),
    ]

    private static let leadership: [Book] = [
        curated("The 7 Habits of Highly Effective People", "Stephen R. Covey", 10079937, .leadership),
        curated("Radical Candor", "Kim Scott", 8088432, .leadership),
        curated("The Effective Executive", "Peter F. Drucker", 15226698, .leadership),
        curated("So Good They Can't Ignore You", "Cal Newport", 9215292, .leadership),
        curated("How to Win Friends and Influence People", "Dale Carnegie", 13314878, .leadership),
        curated("Dare to Lead", "Brené Brown", 10304768, .leadership),
        curated("Leaders Eat Last", "Simon Sinek", 8246311, .leadership),
        curated("Start with Why", "Simon Sinek", 6395237, .leadership),
        curated("The Infinite Game", "Simon Sinek", 10189716, .leadership),
        curated("The Five Dysfunctions of a Team", "Patrick Lencioni", 549590, .leadership),
        curated("The Advantage", "Patrick Lencioni", 9262333, .leadership),
        curated("Extreme Ownership", "Jocko Willink and Leif Babin", 12835042, .leadership),
        curated("Turn the Ship Around!", "L. David Marquet", 8142531, .leadership),
        curated("Multipliers", "Liz Wiseman", 9265081, .leadership),
        curated("The Culture Code", "Daniel Coyle", 10242550, .leadership),
        curated("Good to Great", "Jim Collins", 7431270, .leadership),
        curated("Built to Last", "Jim Collins and Jerry I. Porras", 684195, .leadership),
        curated("First, Break All the Rules", "Marcus Buckingham and Curt Coffman", 427610, .leadership),
        curated("The Leadership Challenge", "James M. Kouzes and Barry Z. Posner", 548022, .leadership),
        curated("On Becoming a Leader", "Warren Bennis", 465469, .leadership),
        curated("The 21 Irrefutable Laws of Leadership", "John C. Maxwell", 1465659, .leadership),
        curated("The Making of a Manager", "Julie Zhuo", 8805106, .leadership),
        curated("The Manager's Path", "Camille Fournier", 8667291, .leadership),
        curated("An Elegant Puzzle", "Will Larson", 9260083, .leadership),
        curated("Trillion Dollar Coach", "Eric Schmidt, Jonathan Rosenberg, and Alan Eagle", 8797805, .leadership),
        curated("The Coaching Habit", "Michael Bungay Stanier", 12515817, .leadership),
        curated("Crucial Conversations", "Kerry Patterson, Joseph Grenny, Ron McMillan, and Al Switzler", 1711809, .leadership),
        curated("Difficult Conversations", "Douglas Stone, Bruce Patton, and Sheila Heen", 2555094, .leadership),
        curated("Thanks for the Feedback", "Douglas Stone and Sheila Heen", 9549524, .leadership),
        curated("Nonviolent Communication", "Marshall B. Rosenberg", 940686, .leadership),
        curated("The Speed of Trust", "Stephen M.R. Covey", 481352, .leadership),
        curated("Emotional Intelligence", "Daniel Goleman", 1359485, .leadership),
        curated("Primal Leadership", "Daniel Goleman, Richard Boyatzis, and Annie McKee", 863982, .leadership),
        curated("What Got You Here Won't Get You There", "Marshall Goldsmith", 749692, .leadership),
        curated("The First 90 Days", "Michael D. Watkins", 863960, .leadership),
        curated("It's Your Ship", "D. Michael Abrashoff", 12196283, .leadership),
        curated("Legacy", "James Kerr", 10491486, .leadership),
        curated("The Score Takes Care of Itself", "Bill Walsh", 9522341, .leadership),
        curated("Wooden on Leadership", "John Wooden", 60373, .leadership),
        curated("Ego Is the Enemy", "Ryan Holiday", 12447129, .leadership),
        curated("The 48 Laws of Power", "Robert Greene", 6424160, .leadership),
        curated("No Rules Rules", "Reed Hastings and Erin Meyer", 10524294, .leadership),
        curated("Powerful", "Patty McCord", 10720773, .leadership),
        curated("Setting the Table", "Danny Meyer", 33989, .leadership),
        curated("Creativity, Inc.", "Ed Catmull", 13124793, .leadership),
        curated("The Ride of a Lifetime", "Robert Iger", 8788773, .leadership),
        curated("Nine Lies About Work", "Marcus Buckingham and Ashley Goodall", 8798836, .leadership),
        curated("Act Like a Leader, Think Like a Leader", "Herminia Ibarra", 13123527, .leadership),
        curated("Leadership and Self-Deception", "The Arbinger Institute", 831276, .leadership),
        curated("The Servant", "James C. Hunter", 509274, .leadership),
    ]

    private static let startup: [Book] = [
        curated("The Lean Startup", "Eric Ries", 7104760, .startup),
        curated("Zero to One", "Peter Thiel and Blake Masters", 9002334, .startup),
        curated("The Hard Thing About Hard Things", "Ben Horowitz", 7279515, .startup),
        curated("The Mom Test", "Rob Fitzpatrick", 10660557, .startup),
        curated("Founders at Work", "Jessica Livingston", 8257114, .startup),
        curated("Venture Deals", "Brad Feld and Jason Mendelson", 8732100, .startup),
        curated("The $100 Startup", "Chris Guillebeau", 7257004, .startup),
        curated("Rework", "Jason Fried and David Heinemeier Hansson", 6679955, .startup),
        curated("It Doesn't Have to Be Crazy at Work", "Jason Fried and David Heinemeier Hansson", 8359215, .startup),
        curated("Anything You Want", "Derek Sivers", 13065727, .startup),
        curated("Company of One", "Paul Jarvis", 8796506, .startup),
        curated("The Startup Owner's Manual", "Steve Blank and Bob Dorf", 8742256, .startup),
        curated("The Four Steps to the Epiphany", "Steve Blank", 4985314, .startup),
        curated("Crossing the Chasm", "Geoffrey A. Moore", 684159, .startup),
        curated("The Innovator's Dilemma", "Clayton M. Christensen", 9274687, .startup),
        curated("Blitzscaling", "Reid Hoffman and Chris Yeh", 8294642, .startup),
        curated("High Growth Handbook", "Elad Gil", 9205954, .startup),
        curated("Secrets of Sand Hill Road", "Scott Kupor", 14669093, .startup),
        curated("Angel", "Jason Calacanis", 10332729, .startup),
        curated("Shoe Dog", "Phil Knight", 8858487, .startup),
        curated("That Will Never Work", "Marc Randolph", 10663066, .startup),
        curated("The Everything Store", "Brad Stone", 7264584, .startup),
        curated("Delivering Happiness", "Tony Hsieh", 6956287, .startup),
        curated("Lost and Founder", "Rand Fishkin", 10538458, .startup),
        curated("The Art of the Start 2.0", "Guy Kawasaki", 12209126, .startup),
        curated("Running Lean", "Ash Maurya", 8122897, .startup),
        curated("Traction: How Any Startup Can Achieve Explosive Customer Growth", "Gabriel Weinberg and Justin Mares", 9364675, .startup),
        curated("The Founder's Dilemmas", "Noam Wasserman", 12893128, .startup),
        curated("The Power Law", "Sebastian Mallaby", 12855991, .startup),
        curated("Start Small, Stay Small", "Rob Walling", 7010380, .startup),
        curated("The SaaS Playbook", "Rob Walling", 14624002, .startup),
        curated("Zero to Sold", "Arvid Kahl", 10231146, .startup),
        curated("The Minimalist Entrepreneur", "Sahil Lavingia", 10846857, .startup),
        curated("The Cold Start Problem", "Andrew Chen", 10607120, .startup),
        curated("Play Bigger", "Al Ramadan, Dave Peterson, Christopher Lochhead, and Kevin Maney", 13461522, .startup),
        curated("Behind the Cloud", "Marc Benioff", 6926229, .startup),
        curated("Elon Musk", "Ashlee Vance", 8463846, .startup),
        curated("Steve Jobs", "Walter Isaacson", 12374726, .startup),
        curated("Super Pumped", "Mike Isaac", 8777999, .startup),
        curated("Bad Blood", "John Carreyrou", 12735651, .startup),
        curated("The Upstarts", "Brad Stone", 10243221, .startup),
        curated("Hatching Twitter", "Nick Bilton", 7275462, .startup),
        curated("The Airbnb Story", "Leigh Gallagher", 8133669, .startup),
        curated("Masters of Scale", "Reid Hoffman", 11974815, .startup),
        curated("Disciplined Entrepreneurship", "Bill Aulet", 14861363, .startup),
        curated("Will It Fly?", "Pat Flynn", 10453400, .startup),
        curated("Hackers & Painters", "Paul Graham", 388913, .startup),
        curated("The Launch Pad", "Randall Stross", 9714962, .startup),
        curated("Lean Analytics", "Alistair Croll and Benjamin Yoskovitz", 7863278, .startup),
        curated("Built to Sell", "John Warrillow", 15162903, .startup),
    ]

    private static let product: [Book] = [
        curated("Inspired", "Marty Cagan", 9700654, .product),
        curated("Empowered", "Marty Cagan and Chris Jones", 10847862, .product),
        curated("Continuous Discovery Habits", "Teresa Torres", 11136152, .product),
        curated("Obviously Awesome", "April Dunford", 10194369, .product),
        curated("The Lean Product Playbook", "Dan Olsen", 14816612, .product),
        curated("Hooked", "Nir Eyal", 12511799, .product),
        curated("Sprint", "Jake Knapp, John Zeratsky, and Braden Kowitz", 7431269, .product),
        curated("The Design of Everyday Things", "Don Norman", 7841556, .product),
        curated("Don't Make Me Think", "Steve Krug", 554640, .product),
        curated("Lean UX", "Jeff Gothelf and Josh Seiden", 7534763, .product),
        curated("User Story Mapping", "Jeff Patton", 8206841, .product),
        curated("Escaping the Build Trap", "Melissa Perri", 10320665, .product),
        curated("Product-Led Growth", "Wes Bush", 12445239, .product),
        curated("Positioning", "Al Ries and Jack Trout", 55745, .product),
        curated("Competing Against Luck", "Clayton M. Christensen", 8138391, .product),
        curated("When Coffee and Kale Compete", "Alan Klement", nil, .product),
        curated("Shape Up", "Ryan Singer", 12600273, .product),
        curated("Making Things Happen", "Scott Berkun", 5076316, .product),
        curated("Cracking the PM Interview", "Gayle Laakmann McDowell and Jackie Bavaro", 7793723, .product),
        curated("Decode and Conquer", "Lewis C. Lin", 9292312, .product),
        curated("Swipe to Unlock", "Neel Mehta, Aditya Agashe, and Parth Detroja", 10215881, .product),
        curated("Hacking Growth", "Sean Ellis and Morgan Brown", 14377164, .product),
        curated("Product Management in Practice", "Matt LeMay", 13161220, .product),
        curated("Badass: Making Users Awesome", "Kathy Sierra", 8276337, .product),
        curated("Creative Selection", "Ken Kocienda", 10128109, .product),
        curated("Build", "Tony Fadell", 12742378, .product),
        curated("Working Backwards", "Colin Bryar and Bill Carr", 10297403, .product),
        curated("The Innovator's Solution", "Clayton M. Christensen and Michael E. Raynor", 834812, .product),
        curated("Blue Ocean Strategy", "W. Chan Kim and Renée Mauborgne", 8219313, .product),
        curated("7 Powers", "Hamilton Helmer", 10208801, .product),
        curated("Understanding Michael Porter", "Joan Magretta", 10535805, .product),
        curated("Platform Revolution", "Geoffrey G. Parker, Marshall W. Van Alstyne, and Sangeet Paul Choudary", 11390852, .product),
        curated("Monetizing Innovation", "Madhavan Ramanujam and Georg Tacke", 13744862, .product),
        curated("The Messy Middle", "Scott Belsky", 14774474, .product),
        curated("Radical Product Thinking", "Radhika Dutt", 11693277, .product),
        curated("Product Roadmaps Relaunched", "C. Todd Lombardo", 8876578, .product),
        curated("Outcomes Over Output", "Josh Seiden", nil, .product),
        curated("The Right It", "Alberto Savoia", 8797518, .product),
        curated("Testing Business Ideas", "David J. Bland and Alexander Osterwalder", 9388387, .product),
        curated("Business Model Generation", "Alexander Osterwalder and Yves Pigneur", 6675500, .product),
        curated("The Mythical Man-Month", "Frederick P. Brooks Jr.", 6915361, .product),
        curated("About Face", "Alan Cooper", 1239160, .product),
        curated("100 Things Every Designer Needs to Know About People", "Susan Weinschenk", 8727716, .product),
        curated("Universal Principles of Design", "William Lidwell", 868272, .product),
        curated("Actionable Gamification", "Yu-kai Chou", 12031229, .product),
        curated("Purple Cow", "Seth Godin", 866008, .product),
        curated("Zag", "Marty Neumeier", 194033, .product),
        curated("Different", "Youngme Moon", 9096659, .product),
        curated("Alchemy", "Rory Sutherland", 10184444, .product),
        curated("The Experience Economy", "B. Joseph Pine II and James H. Gilmore", 668140, .product),
    ]

    private static let sales: [Book] = [
        curated("Never Split the Difference", "Chris Voss", 8365942, .sales),
        curated("SPIN Selling", "Neil Rackham", 55114, .sales),
        curated("Influence", "Robert B. Cialdini", 431011, .sales),
        curated("To Sell Is Human", "Daniel H. Pink", 10297418, .sales),
        curated("The Challenger Sale", "Matthew Dixon and Brent Adamson", 7970492, .sales),
        curated("Fanatical Prospecting", "Jeb Blount", 12685538, .sales),
        curated("New Sales. Simplified.", "Mike Weinberg", 12519199, .sales),
        curated("The Little Red Book of Selling", "Jeffrey Gitomer", 7600338, .sales),
        curated("How I Raised Myself from Failure to Success in Selling", "Frank Bettger", 408877, .sales),
        curated("Secrets of Closing the Sale", "Zig Ziglar", 561872, .sales),
        curated("The Psychology of Selling", "Brian Tracy", 13270498, .sales),
        curated("Way of the Wolf", "Jordan Belfort", 8814984, .sales),
        curated("Sell or Be Sold", "Grant Cardone", 13181453, .sales),
        curated("The 10X Rule", "Grant Cardone", 9978588, .sales),
        curated("Pitch Anything", "Oren Klaff", 7304551, .sales),
        curated("Getting to Yes", "Roger Fisher and William Ury", 96165, .sales),
        curated("Getting Past No", "William Ury", 369545, .sales),
        curated("Never Lose a Customer Again", "Joey Coleman", 8843037, .sales),
        curated("Pre-Suasion", "Robert Cialdini", 7880005, .sales),
        curated("Gap Selling", "Keenan", 9670355, .sales),
        curated("The Sales Acceleration Formula", "Mark Roberge", 10657756, .sales),
        curated("Predictable Revenue", "Aaron Ross and Marylou Tyler", 7441152, .sales),
        curated("From Impossible to Inevitable", "Aaron Ross and Jason Lemkin", 13288766, .sales),
        curated("The Ultimate Sales Machine", "Chet Holmes", 1860749, .sales),
        curated("Exactly What to Say", "Phil M. Jones", 15092604, .sales),
        curated("The Transparency Sale", "Todd Caponi", 9192127, .sales),
        curated("Sell with a Story", "Paul Smith", 11266562, .sales),
        curated("Building a StoryBrand", "Donald Miller", 8458703, .sales),
        curated("They Ask, You Answer", "Marcus Sheridan", 13158050, .sales),
        curated("This Is Marketing", "Seth Godin", 14624926, .sales),
        curated("Contagious", "Jonah Berger", 9039370, .sales),
        curated("Made to Stick", "Chip Heath and Dan Heath", 7004880, .sales),
        curated("The Go-Giver", "Bob Burg and John David Mann", 6463899, .sales),
        curated("The Greatest Salesman in the World", "Og Mandino", 8458650, .sales),
        curated("Smart Calling", "Art Sobczak", 13257203, .sales),
        curated("Insight Selling", "Mike Schultz and John E. Doerr", 12935497, .sales),
        curated("The Qualified Sales Leader", "John McMahon", 10880129, .sales),
        curated("Demand-Side Sales 101", "Bob Moesta", 10455373, .sales),
        curated("$100M Offers", "Alex Hormozi", 11948182, .sales),
        curated("$100M Leads", "Alex Hormozi", 14796132, .sales),
        curated("The JOLT Effect", "Matthew Dixon and Ted McKenna", nil, .sales),
        curated("Sell Like Crazy", "Sabri Suby", 10352021, .sales),
        curated("Founding Sales", "Peter Kazanjy", nil, .sales),
        curated("Yes!: 50 Scientifically Proven Ways to Be Persuasive", "Noah J. Goldstein, Steve J. Martin, and Robert B. Cialdini", 5424007, .sales),
        curated("Jab, Jab, Jab, Right Hook", "Gary Vaynerchuk", 11955993, .sales),
        curated("Sales EQ", "Jeb Blount", nil, .sales),
        curated("Selling to Big Companies", "Jill Konrath", 1804885, .sales),
        curated("The New Strategic Selling", "Robert B. Miller and Stephen E. Heiman", 6888865, .sales),
        curated("Solution Selling", "Michael T. Bosworth", 541472, .sales),
        curated("Eat Their Lunch", "Anthony Iannarino", 8792314, .sales),
    ]

    private static let careers: [Book] = [
        curated("Designing Your Life", "Bill Burnett and Dave Evans", 8760239, .careers),
        curated("The Squiggly Career", "Helen Tupper and Sarah Ellis", 10901750, .careers),
        curated("Working Identity", "Herminia Ibarra", 834800, .careers),
        curated("Range", "David Epstein", 8782615, .careers),
        curated("Linchpin", "Seth Godin", 8754365, .careers),
        curated("The Startup of You", "Reid Hoffman and Ben Casnocha", 7149195, .careers),
        curated("Never Eat Alone", "Keith Ferrazzi", 6802201, .careers),
        curated("Give and Take", "Adam Grant", 7391212, .careers),
        curated("Originals", "Adam Grant", 8870353, .careers),
        curated("Think Again", "Adam Grant", 10470266, .careers),
        curated("Ultralearning", "Scott H. Young", 10156205, .careers),
        curated("What Color Is Your Parachute?", "Richard N. Bolles", 4771065, .careers),
        curated("StrengthsFinder 2.0", "Tom Rath", 874927, .careers),
        curated("Pivot", "Jenny Blake", 7940358, .careers),
        curated("Body of Work", "Pamela Slim", 10206236, .careers),
        curated("The Pathless Path", "Paul Millerd", 14840711, .careers),
        curated("The Long Game", "Dorie Clark", 11998647, .careers),
        curated("Reinventing You", "Dorie Clark", 7807096, .careers),
        curated("The Defining Decade", "Meg Jay", 12132013, .careers),
        curated("Lean In", "Sheryl Sandberg", 7254305, .careers),
        curated("Nice Girls Don't Get the Corner Office", "Lois P. Frankel", 286348, .careers),
        curated("The Unspoken Rules", "Gorick Ng", 10900019, .careers),
        curated("Steal Like an Artist", "Austin Kleon", 7244512, .careers),
        curated("Show Your Work!", "Austin Kleon", 7284188, .careers),
        curated("Big Magic", "Elizabeth Gilbert", 7434843, .careers),
        curated("The Element", "Ken Robinson", 7280801, .careers),
        curated("Mastery", "Robert Greene", 7561012, .careers),
        curated("The Crossroads of Should and Must", "Elle Luna", 8138390, .careers),
        curated("An Astronaut's Guide to Life on Earth", "Chris Hadfield", 7459498, .careers),
        curated("The Art of Work", "Jeff Goins", 7345903, .careers),
        curated("48 Days to the Work You Love", "Dan Miller", 14437044, .careers),
        curated("The 2-Hour Job Search", "Steve Dalton", 10658217, .careers),
        curated("The Adventures of Johnny Bunko", "Daniel H. Pink", 2961195, .careers),
        curated("Do What You Are", "Paul D. Tieger", 3971531, .careers),
        curated("Great at Work", "Morten T. Hansen", 8302298, .careers),
        curated("Chop Wood Carry Water", "Joshua Medcalf", 10457966, .careers),
        curated("The Practice", "Seth Godin", 10327322, .careers),
        curated("Playing Big", "Tara Mohr", 8991591, .careers),
        curated("Presence", "Amy Cuddy", 8831349, .careers),
        curated("Quiet", "Susan Cain", 7079753, .careers),
        curated("Bullshit Jobs", "David Graeber", 8798647, .careers),
        curated("The Good Enough Job", "Simone Stolzoff", nil, .careers),
        curated("Out of Office", "Charlie Warzel and Anne Helen Petersen", 10872458, .careers),
        curated("Remote", "Jason Fried and David Heinemeier Hansson", 8142534, .careers),
        curated("The New Rules of Work", "Alexandra Cavoulacos and Kathryn Minshew", 7688780, .careers),
        curated("Designing Your Work Life", "Bill Burnett and Dave Evans", 9297046, .careers),
        curated("How Will You Measure Your Life?", "Clayton M. Christensen", 8847058, .careers),
        curated("The Third Door", "Alex Banayan", 10324820, .careers),
        curated("Taking the Work Out of Networking", "Karen Wickre", 9242544, .careers),
        curated("The Happiness Equation", "Neil Pasricha", 13056729, .careers),
    ]

    private static func curated(_ title: String, _ author: String, _ coverID: Int?, _ category: BookCategory) -> Book {
        Book(
            id: Book.slug(fromTitle: title),
            title: title,
            shortTitle: title.count > 30 ? String(title.prefix(27)) + "..." : title,
            author: author,
            angle: "A book by \(author).",
            category: category,
            keywords: [],
            coverColors: [
                Color(red: 0.14, green: 0.16, blue: 0.20),
                Color(red: 0.55, green: 0.60, blue: 0.65)
            ],
            coverURL: coverID.flatMap { URL(string: "https://covers.openlibrary.org/b/id/\($0)-L.jpg") }
        )
    }
}
