@preconcurrency import AVFoundation
import CryptoKit
import Foundation
import MediaPlayer

// Plays the shared digest MP3 for a book. Audio is generated once server-side
// (see supabase/functions/generate-digest) and downloaded into
// DigestAudioStore; pre-backend digests keep playing from the legacy combined
// .m4a cache. Playback is always a single local file.
@MainActor
final class SpeechController: NSObject, ObservableObject {
    enum LoadingStage: Equatable {
        case requesting
        case generatingAudio
        case downloading(Double)
    }

    @Published private(set) var isSpeaking = false
    @Published private(set) var isPaused = false
    @Published private(set) var isLoading = false
    @Published private(set) var currentBookID: String?
    @Published private(set) var currentTitle: String?
    @Published private(set) var currentTime: TimeInterval = 0
    @Published private(set) var duration: TimeInterval = 0
    @Published private(set) var downloadedDuration: TimeInterval = 0
    @Published private(set) var loadingStage: LoadingStage?
    @Published private(set) var errorMessage: String?

    private var audioPlayer: AVAudioPlayer?
    private var preparationTask: Task<Void, Never>?
    private var progressTimer: Timer?
    private var hasActiveAudioSession = false
    private var interruptionObserver: (any NSObjectProtocol)?
    private var nowPlayingArtwork: MPMediaItemArtwork?

    private let backend: SupabaseService

    init(backend: SupabaseService) {
        self.backend = backend
    }

    var downloadProgress: Double {
        if case .downloading(let fraction) = loadingStage {
            return fraction
        }
        return audioPlayer != nil ? 1 : 0
    }

    // The ElevenLabs key is only needed when this book's audio hasn't been
    // generated by anyone yet; playing existing shared audio is free.
    func speak(_ text: String, book: Book, apiKey: String) {
        let trimmedText = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedText.isEmpty else {
            return
        }

        if currentBookID == book.id, audioPlayer != nil {
            if duration > 0, currentTime >= duration {
                seek(to: 0)
            }

            do {
                try startPlayback()
            } catch {
                errorMessage = error.localizedDescription
                resetPlaybackState(keepError: true)
            }
            return
        }

        stop()
        currentBookID = book.id
        currentTitle = book.title
        errorMessage = nil
        isLoading = true
        loadArtwork(for: book.id)

        preparationTask = Task { [weak self] in
            guard let self else {
                return
            }

            do {
                try await preparePlayback(for: trimmedText, book: book, apiKey: apiKey)
            } catch is CancellationError {
                resetPlaybackState()
            } catch {
                errorMessage = error.localizedDescription
                resetPlaybackState(keepError: true)
            }

            preparationTask = nil
        }
    }

    func pause() {
        guard audioPlayer?.isPlaying == true else {
            return
        }

        audioPlayer?.pause()
        syncPlaybackProgress()
        stopProgressTimer()
        isPaused = true
        isSpeaking = false
        updateNowPlayingInfo()
        savePlaybackPosition()
    }

    func continueSpeaking() {
        guard audioPlayer != nil, isPaused else {
            return
        }

        do {
            try startPlayback()
        } catch {
            errorMessage = error.localizedDescription
            resetPlaybackState(keepError: true)
        }
    }

    func seek(to time: TimeInterval) {
        guard let audioPlayer else {
            return
        }

        let boundedTime = min(max(time, 0), max(duration, 0))
        guard boundedTime.isFinite else {
            return
        }

        audioPlayer.currentTime = boundedTime
        currentTime = boundedTime
        updateNowPlayingInfo()
    }

    func skip(by delta: TimeInterval) {
        seek(to: currentPlaybackTime() + delta)
    }

    func stop() {
        savePlaybackPosition()
        preparationTask?.cancel()
        preparationTask = nil
        audioPlayer?.stop()
        resetPlaybackState()
    }

    func savePlaybackPosition() {
        guard let bookID = currentBookID, duration > 0 else { return }
        let time = currentPlaybackTime()
        if time >= duration - 1 {
            PlaybackPositionStore.clear(for: bookID)
            FinishedBooksStore.markFinished(bookID)
        } else {
            PlaybackPositionStore.save(time: time, duration: duration, for: bookID)
        }
    }

    private func preparePlayback(for text: String, book: Book, apiKey: String) async throws {
        let bookID = book.id

        if let localURL = DigestAudioStore.url(for: bookID) ?? Self.legacyCombinedAudioURL(for: text) {
            try beginLocalPlayback(url: localURL, bookID: bookID)
            return
        }

        loadingStage = .requesting

        var row = try await backend.fetchDigest(bookID: bookID)
        try Task.checkCancellation()

        if row?.audioStatus != .ready || row?.audioStoragePath == nil {
            let trimmedKey = apiKey.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmedKey.isEmpty else {
                throw SpeechControllerError.missingElevenLabsKey
            }

            try await backend.requestAudioGeneration(book: book, elevenLabsKey: trimmedKey)
            loadingStage = .generatingAudio
            row = try await backend.waitForAudio(bookID: bookID)
            try Task.checkCancellation()
        }

        guard let storagePath = row?.audioStoragePath else {
            throw SpeechControllerError.audioNotReady
        }

        loadingStage = .downloading(0)
        let signedURL = try await backend.signedAudioURL(path: storagePath)
        let fileURL = try await DigestAudioStore.download(from: signedURL, for: bookID) { [weak self] fraction in
            guard let self, self.currentBookID == bookID else { return }
            self.loadingStage = .downloading(fraction)
        }
        try Task.checkCancellation()

        guard currentBookID == bookID else {
            return
        }

        try beginLocalPlayback(url: fileURL, bookID: bookID)
    }

    private func beginLocalPlayback(url: URL, bookID: String) throws {
        loadingStage = nil

        let savedPosition = PlaybackPositionStore.savedPosition(for: bookID)
        let startTime = savedPosition?.time ?? 0

        try replacePlayer(with: url, at: startTime)
        duration = audioPlayer?.duration ?? 0
        downloadedDuration = duration
        currentTime = min(startTime, duration)
        try startPlayback()
    }

    // Pre-backend audio was combined on-device into an .m4a keyed by
    // model/voice/text; the voice the user had selected back then is still in
    // UserDefaults even though the setting is gone.
    private static func legacyCombinedAudioURL(for text: String) -> URL? {
        let voice = UserDefaults.standard.string(forKey: "elevenLabs.speechVoice") ?? "lUTamkMw7gOzZbFIwmq4"
        return CombinedSpeechCache.url(text: text, model: "eleven_flash_v2_5", voice: voice)
    }

    private func startPlayback() throws {
        guard let audioPlayer else {
            return
        }

        try configureAudioSession()
        configureRemoteCommands()
        _ = audioPlayer.play()
        isLoading = false
        isSpeaking = true
        isPaused = false
        startProgressTimer()
        syncPlaybackProgress()
        updateNowPlayingInfo()
    }

    private func replacePlayer(with url: URL, at time: TimeInterval) throws {
        let player = try AVAudioPlayer(contentsOf: url)
        player.delegate = self
        player.prepareToPlay()
        player.currentTime = min(max(time, 0), player.duration)

        audioPlayer?.stop()
        audioPlayer = player
    }

    private var positionSaveCounter = 0

    private func startProgressTimer() {
        stopProgressTimer()
        positionSaveCounter = 0

        let timer = Timer(timeInterval: 0.2, repeats: true) { [weak self] _ in
            Task { @MainActor in
                guard let self else { return }
                self.syncPlaybackProgress()
                self.positionSaveCounter += 1
                if self.positionSaveCounter >= 25 {
                    self.positionSaveCounter = 0
                    self.savePlaybackPosition()
                }
            }
        }
        timer.tolerance = 0.05
        RunLoop.main.add(timer, forMode: .common)
        progressTimer = timer
    }

    private func stopProgressTimer() {
        progressTimer?.invalidate()
        progressTimer = nil
    }

    private func syncPlaybackProgress() {
        guard let audioPlayer else {
            return
        }

        currentTime = audioPlayer.currentTime
        duration = audioPlayer.duration
    }

    private func currentPlaybackTime() -> TimeInterval {
        audioPlayer?.currentTime ?? 0
    }

    private func resetPlaybackState(keepError: Bool = false) {
        preparationTask?.cancel()
        preparationTask = nil
        isLoading = false
        isSpeaking = false
        isPaused = false
        currentBookID = nil
        currentTitle = nil
        currentTime = 0
        duration = 0
        downloadedDuration = 0
        loadingStage = nil
        nowPlayingArtwork = nil
        stopProgressTimer()
        audioPlayer = nil
        tearDownRemoteCommands()
        clearNowPlayingInfo()
        deactivateAudioSession()

        if !keepError {
            errorMessage = nil
        }
    }

    private func configureAudioSession() throws {
        let session = AVAudioSession.sharedInstance()

        // Use the playback category so spoken audio continues when the app backgrounds or the screen locks.
        try session.setCategory(.playback, mode: .spokenAudio)

        if !hasActiveAudioSession {
            try session.setActive(true)
            hasActiveAudioSession = true
        }

        registerInterruptionObserver()
    }

    private func registerInterruptionObserver() {
        guard interruptionObserver == nil else { return }

        interruptionObserver = NotificationCenter.default.addObserver(
            forName: AVAudioSession.interruptionNotification,
            object: AVAudioSession.sharedInstance(),
            queue: .main
        ) { [weak self] notification in
            Task { @MainActor in
                self?.handleInterruption(notification)
            }
        }
    }

    private func handleInterruption(_ notification: Notification) {
        guard let typeValue = notification.userInfo?[AVAudioSessionInterruptionTypeKey] as? UInt,
              let type = AVAudioSession.InterruptionType(rawValue: typeValue) else { return }

        switch type {
        case .began:
            if isSpeaking {
                audioPlayer?.pause()
                syncPlaybackProgress()
                stopProgressTimer()
                isPaused = true
                isSpeaking = false
                updateNowPlayingInfo()
                savePlaybackPosition()
            }

        case .ended:
            guard isPaused else { return }
            let shouldResume = (notification.userInfo?[AVAudioSessionInterruptionOptionKey] as? UInt)
                .map { AVAudioSession.InterruptionOptions(rawValue: $0).contains(.shouldResume) } ?? false
            if shouldResume {
                do {
                    try startPlayback()
                } catch {
                    errorMessage = error.localizedDescription
                    resetPlaybackState(keepError: true)
                }
            }

        @unknown default:
            break
        }
    }

    private var remoteCommandsConfigured = false

    private func configureRemoteCommands() {
        guard !remoteCommandsConfigured else { return }
        remoteCommandsConfigured = true

        let commandCenter = MPRemoteCommandCenter.shared()

        commandCenter.playCommand.addTarget { [weak self] _ in
            Task { @MainActor in self?.continueSpeaking() }
            return .success
        }

        commandCenter.pauseCommand.addTarget { [weak self] _ in
            Task { @MainActor in self?.pause() }
            return .success
        }

        commandCenter.togglePlayPauseCommand.addTarget { [weak self] _ in
            Task { @MainActor in
                guard let self else { return }
                if self.isSpeaking {
                    self.pause()
                } else if self.isPaused {
                    self.continueSpeaking()
                }
            }
            return .success
        }

        commandCenter.skipForwardCommand.preferredIntervals = [15]
        commandCenter.skipForwardCommand.addTarget { [weak self] _ in
            Task { @MainActor in self?.skip(by: 15) }
            return .success
        }

        commandCenter.skipBackwardCommand.preferredIntervals = [15]
        commandCenter.skipBackwardCommand.addTarget { [weak self] _ in
            Task { @MainActor in self?.skip(by: -15) }
            return .success
        }

        commandCenter.changePlaybackPositionCommand.addTarget { [weak self] event in
            guard let event = event as? MPChangePlaybackPositionCommandEvent else { return .commandFailed }
            Task { @MainActor in self?.seek(to: event.positionTime) }
            return .success
        }
    }

    private func tearDownRemoteCommands() {
        guard remoteCommandsConfigured else { return }
        remoteCommandsConfigured = false

        let commandCenter = MPRemoteCommandCenter.shared()
        commandCenter.playCommand.removeTarget(nil)
        commandCenter.pauseCommand.removeTarget(nil)
        commandCenter.togglePlayPauseCommand.removeTarget(nil)
        commandCenter.skipForwardCommand.removeTarget(nil)
        commandCenter.skipBackwardCommand.removeTarget(nil)
        commandCenter.changePlaybackPositionCommand.removeTarget(nil)
    }

    private func loadArtwork(for bookID: String) {
        guard let book = Book.catalog.first(where: { $0.id == bookID })
                ?? BookStore.loadPersistedBooksList().first(where: { $0.id == bookID }) else { return }

        Task { [weak self] in
            guard let image = await BookCoverService.shared.image(for: book) else { return }
            guard let self, self.currentBookID == bookID else { return }
            self.nowPlayingArtwork = MPMediaItemArtwork(boundsSize: image.size) { _ in image }
            self.updateNowPlayingInfo()
        }
    }

    private func updateNowPlayingInfo() {
        var info = [String: Any]()
        info[MPMediaItemPropertyTitle] = currentTitle ?? "Book Digest"
        info[MPNowPlayingInfoPropertyElapsedPlaybackTime] = currentTime
        info[MPMediaItemPropertyPlaybackDuration] = duration
        info[MPNowPlayingInfoPropertyPlaybackRate] = isSpeaking ? 1.0 : 0.0
        if let nowPlayingArtwork {
            info[MPMediaItemPropertyArtwork] = nowPlayingArtwork
        }
        MPNowPlayingInfoCenter.default().nowPlayingInfo = info
    }

    private func clearNowPlayingInfo() {
        MPNowPlayingInfoCenter.default().nowPlayingInfo = nil
    }

    private func deactivateAudioSession() {
        if let interruptionObserver {
            NotificationCenter.default.removeObserver(interruptionObserver)
            self.interruptionObserver = nil
        }

        guard hasActiveAudioSession else {
            return
        }

        do {
            try AVAudioSession.sharedInstance().setActive(false, options: [.notifyOthersOnDeactivation])
        } catch {
            // Keep teardown best-effort so stop/failure paths do not surface a secondary error.
        }

        hasActiveAudioSession = false
    }
}

extension SpeechController: AVAudioPlayerDelegate {
    nonisolated func audioPlayerDidFinishPlaying(_ player: AVAudioPlayer, successfully flag: Bool) {
        Task { @MainActor in
            guard flag else {
                errorMessage = "Audio playback did not finish successfully."
                resetPlaybackState(keepError: true)
                return
            }

            if let bookID = currentBookID {
                PlaybackPositionStore.clear(for: bookID)
                FinishedBooksStore.markFinished(bookID)
            }
            resetPlaybackState()
        }
    }

    nonisolated func audioPlayerDecodeErrorDidOccur(_ player: AVAudioPlayer, error: Error?) {
        Task { @MainActor in
            errorMessage = error?.localizedDescription ?? "Audio playback failed."
            resetPlaybackState(keepError: true)
        }
    }
}

private enum SpeechControllerError: LocalizedError {
    case missingElevenLabsKey
    case audioNotReady

    var errorDescription: String? {
        switch self {
        case .missingElevenLabsKey:
            return "This book has no shared audio yet. Add an ElevenLabs API key in Settings to generate it."
        case .audioNotReady:
            return "The audio isn't ready yet. Try again in a moment."
        }
    }
}

// Read-only remnant of the pre-backend on-device pipeline: combined .m4a
// files keyed by SHA-256 of "model\nvoice\ntext". Kept so digests generated
// before the shared backend still play offline. No new files are written.
private enum CombinedSpeechCache {
    private static let directoryName = "CombinedSpeechCache"

    static func url(text: String, model: String, voice: String) -> URL? {
        guard let outputURL = fileURL(text: text, model: model, voice: voice),
              FileManager.default.fileExists(atPath: outputURL.path) else {
            return nil
        }

        return outputURL
    }

    private static func cacheKey(text: String, model: String, voice: String) -> String {
        let cacheInput = "\(model)\n\(voice)\n\(text)"
        let digest = SHA256.hash(data: Data(cacheInput.utf8))
        return digest.map { String(format: "%02x", $0) }.joined()
    }

    private static func fileURL(text: String, model: String, voice: String) -> URL? {
        guard let directoryURL = directoryURL() else {
            return nil
        }

        return directoryURL.appendingPathComponent(cacheKey(text: text, model: model, voice: voice))
            .appendingPathExtension("m4a")
    }

    private static func directoryURL() -> URL? {
        try? FileManager.default.url(
            for: .applicationSupportDirectory,
            in: .userDomainMask,
            appropriateFor: nil,
            create: true
        )
        .appendingPathComponent(Bundle.main.bundleIdentifier ?? "BookDigest", isDirectory: true)
        .appendingPathComponent(directoryName, isDirectory: true)
    }
}

enum PlaybackPositionStore {
    private static let prefix = "playback.position."
    private static let durationPrefix = "playback.duration."

    static func save(time: TimeInterval, duration: TimeInterval, for bookID: String) {
        UserDefaults.standard.set(time, forKey: prefix + bookID)
        UserDefaults.standard.set(duration, forKey: durationPrefix + bookID)
    }

    static func savedPosition(for bookID: String) -> (time: TimeInterval, duration: TimeInterval)? {
        let time = UserDefaults.standard.double(forKey: prefix + bookID)
        let duration = UserDefaults.standard.double(forKey: durationPrefix + bookID)
        guard time > 0, duration > 0 else { return nil }
        return (time, duration)
    }

    static func clear(for bookID: String) {
        UserDefaults.standard.removeObject(forKey: prefix + bookID)
        UserDefaults.standard.removeObject(forKey: durationPrefix + bookID)
    }
}
